name: Deploy to Cloud Run

on:
  workflow_dispatch:

env:
  PROJECT_ID: job-tracker-pro-480917
  REGION: asia-south1
  REPO_NAME: my-repo 
  SERVICE_NAME: jobtracker-service
  IMAGE_NAME: my-java-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Docker Auth
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build and Push Container
      run: |
        TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        docker build -t $TAG .
        docker push $TAG
        echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

    - name: Update Service YAML
      run: |
        # Replace the hardcoded image line with the new dynamic tag
        sed -i "s|image: .*|image: ${{ env.IMAGE_TAG }}|g" service.yaml
        cat service.yaml # Optional: verify content in logs

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        metadata: service.yaml
        region: ${{ env.REGION }}
